apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app.k0s.io
spec:
  secretName: app.k0s.io
  dnsNames:
  - 'app.k0s.io'
  issuerRef:
    name: letsencrypt
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - args:
        - |
          # k0s agent
          h3 server
        ports:
        - containerPort: 4430
          hostPort: 457
          protocol: UDP
        - containerPort: 4430
          protocol: TCP
        env:
        - name: PORT
          value: "4430"
        - name: HOST
          value: app.k0s.io
        - name: ALT_SVC
          value: h3=":457"
        - name: UI
          value: https://k0s.io
        - name: CERT
          value: tls.crt
        - name: KEY
          value: tls.key
        command:
        - bash
        - -c
        image: btwiuse/h3
        imagePullPolicy: Always
        name: app
        volumeMounts:
        - mountPath: /h3
          name: app
      restartPolicy: Always
      volumes:
      - secret:
          secretName: app.k0s.io
        name: app
      - hostPath:
          path: /
        name: chroot
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 4430
    name: tcp
  - port: 4000
    protocol: UDP
    targetPort: 4430
    name: udp
  selector:
    app: app
  sessionAffinity: None
  type: ClusterIP
---
# TODO How to make traefik ingress work with http3?
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: app.k0s.io
spec:
  rules:
  - host: app.k0s.io
    http:
      paths:
      - backend:
          service:
            name: app
            port:
              number: 8000
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - app.k0s.io
    secretName: k0s
